"""v0.5.171: shared HTML-report builder for the admin portal.

Operator: "also allow user to generate report for admin portal
http://san-hp-srv06:5050/admin"

Mirrors the RDMA-session report (utils/rdma_report.py) but for
the server-side admin state. One-click "Export Report" produces
a self-contained HTML file capturing:

  * Host: hostname, kernel, uptime, server version
  * Health: DPDK installed? IOMMU? VFIO modules? Hugepages?
            tx_worker present? Tools (ip, ethtool, ibv_devinfo,
            perftest, dpdk-devbind)
  * Network interfaces: each iface with MAC, IP, speed, MTU,
                       driver, NUMA, PCIe Gen, NIC model
  * RDMA HCAs: each HCA with link rate, MTU, state, PCIe Gen,
              NUMA, IP, driver, vendor, FW, first GID
  * DPDK bind history: timestamps + per-port driver
  * Orphan workers: any untracked tx/rx_worker processes
  * Hugepages: per-NUMA allocation

The output is self-contained (inline CSS, no external assets).
Operators can email / archive / attach to bug reports as-is.

Why separate from the diag_bundle endpoint?
  * diag_bundle = tar.gz of raw artefacts (lspci, ethtool dumps,
    journal slices) for engineering deep-dives.
  * This report = human-readable rendered HTML for sharing /
    archival / quick scan during incident triage.
"""
from __future__ import annotations

from html import escape
from typing import Any, Dict, List, Optional


def build_admin_report_html(
    *,
    snapshot: Dict[str, Any],
    generated_at: str,
    server_version: Optional[str] = None,
) -> str:
    """Render the full HTML document. `snapshot` is a merged dict
    of the data from /api/admin/health + /api/interfaces +
    /api/dpdk/status + /api/rdma/devices + /api/admin/bind_history
    + /api/streams/orphans. The endpoint fetches them via Flask
    test_client and hands the merged result here.

    `generated_at` is the server-side wall-clock at export time
    (caller-provided so the function stays pure / testable).
    `server_version` is the netgen version string (best-effort —
    e.g. from /api/health). Renders as `—` when missing.
    """
    head = _render_head()
    intro = _render_intro(snapshot, generated_at, server_version)
    body = (
        _render_health_section(snapshot)
        + _render_tools_section(snapshot)
        + _render_hugepages_section(snapshot)
        + _render_interfaces_section(snapshot)
        + _render_rdma_section(snapshot)
        + _render_bind_history_section(snapshot)
        + _render_orphans_section(snapshot)
    )
    footer = (
        "<footer>Generated by netgen admin portal. "
        "Self-contained HTML — safe to archive or attach to bug "
        "reports.</footer>"
    )
    return (
        f"<!DOCTYPE html>\n<html lang='en'><head>{head}</head>"
        f"<body><main class='container'>{intro}{body}{footer}</main>"
        f"</body></html>"
    )


# ───── HEAD / INTRO ─────────────────────────────────────────────────


def _render_head() -> str:
    css = """
        :root {
          --fg: #0f172a; --muted: #475569; --line: #cbd5e1;
          --card: #f8fafc; --accent: #1d4ed8;
          --warn: #b45309; --ok: #047857; --err: #b91c1c;
          --stripe: #f1f5f9;
        }
        * { box-sizing: border-box; }
        body {
          font-family: -apple-system, BlinkMacSystemFont, "Segoe UI",
                       Roboto, sans-serif;
          color: var(--fg); background: #fff; margin: 0;
          line-height: 1.5;
        }
        .container { max-width: 1240px; margin: 0 auto; padding: 24px; }
        h1 { font-size: 22px; margin: 0 0 4px; }
        h2 {
          font-size: 15px; margin: 22px 0 8px;
          padding-bottom: 4px;
          border-bottom: 1px solid var(--line);
          color: var(--accent);
        }
        h3 {
          font-size: 12px; margin: 14px 0 6px;
          color: var(--muted);
          text-transform: uppercase; letter-spacing: 0.5px;
          font-weight: 700;
        }
        .meta { color: var(--muted); font-size: 12px; margin-bottom: 16px; }
        .meta strong { color: var(--fg); font-weight: 600; }
        table {
          width: 100%; border-collapse: collapse; margin-top: 6px;
          font-size: 12px;
        }
        th, td { padding: 6px 10px; text-align: left;
          border-bottom: 1px solid var(--line);
        }
        th {
          color: var(--muted); font-weight: 600;
          background: #eef2f7; font-size: 11px;
          text-transform: uppercase; letter-spacing: 0.3px;
        }
        tbody tr:nth-child(even) { background: var(--stripe); }
        td.code, .code {
          font-family: "SF Mono", Menlo, Consolas, monospace;
          font-size: 11px;
        }
        td.num { font-family: "SF Mono", Menlo, Consolas, monospace;
          text-align: right;
        }
        td.dim { color: var(--muted); }
        .pill {
          display: inline-block; padding: 1px 8px; border-radius: 10px;
          font-size: 11px;
        }
        .pill.ok { background: #d1fae5; color: var(--ok); }
        .pill.warn { background: #fef3c7; color: var(--warn); }
        .pill.err { background: #fee2e2; color: var(--err); }
        .pill.dim { background: #f1f5f9; color: var(--muted); }
        /* Mirror of rdma_report.py's PCIe downgrade warning. */
        .pcie-warn {
          background: #fef3c7;
          color: var(--warn);
          font-weight: 600;
        }
        .kv {
          display: grid;
          grid-template-columns: 200px 1fr;
          gap: 4px 12px;
          font-size: 12px;
          margin-top: 4px;
        }
        .kv .k { color: var(--muted); }
        .kv .v { font-family: "SF Mono", Menlo, Consolas, monospace; }
        .empty {
          padding: 12px; background: var(--card); border-radius: 6px;
          color: var(--muted); font-style: italic; font-size: 12px;
        }
        footer { color: var(--muted); font-size: 11px; margin-top: 32px;
          padding-top: 12px; border-top: 1px solid var(--line);
        }
    """
    return (
        f"<meta charset='utf-8'>"
        f"<title>Admin Portal — Session Report</title>"
        f"<style>{css}</style>"
    )


def _render_intro(
    snapshot: Dict[str, Any], generated_at: str,
    server_version: Optional[str],
) -> str:
    health = snapshot.get("health") or {}
    host = health.get("hostname") or "—"
    netgen_ver = server_version or "—"
    port = (health.get("netgen_server") or {}).get("port") or "—"
    return (
        f"<h1>Admin Portal — Session Report</h1>"
        f"<div class='meta'>"
        f"<strong>Host:</strong> {escape(str(host))}"
        f" &middot; <strong>Server port:</strong> {escape(str(port))}"
        f" &middot; <strong>netgen:</strong> "
        f"{escape(str(netgen_ver))}"
        f" &middot; <strong>Generated:</strong> "
        f"{escape(generated_at)}"
        f"</div>"
    )


# ───── HEALTH ───────────────────────────────────────────────────────


def _render_health_section(snapshot: Dict[str, Any]) -> str:
    health = snapshot.get("health") or {}
    dpdk = health.get("dpdk") or {}
    iommu = health.get("iommu") or {}
    vfio = health.get("vfio") or {}
    hp = health.get("hugepages") or {}
    tx = health.get("tx_worker") or {}
    rows = [
        ("DPDK installed",
         _ok_pill(dpdk.get("installed")),
         dpdk.get("version") or "—"),
        ("IOMMU enabled",
         _ok_pill(iommu.get("enabled")),
         _short(iommu.get("cmdline_excerpt") or "", 80)),
        ("vfio-pci",
         _ok_pill(vfio.get("vfio_pci")),
         "loaded" if vfio.get("vfio_pci") else "missing"),
        ("vfio_iommu_type1",
         _ok_pill(vfio.get("vfio_iommu_type1")),
         "loaded" if vfio.get("vfio_iommu_type1")
         else "missing"),
        ("tx_worker binary",
         _ok_pill(tx.get("present")),
         tx.get("path") or "—"),
        ("Install running?",
         _warn_pill(health.get("install_running")),
         "yes" if health.get("install_running") else "idle"),
    ]
    body = "".join(
        f"<tr><td>{escape(label)}</td>"
        f"<td>{pill}</td>"
        f"<td class='code dim'>{escape(str(detail))}</td></tr>"
        for label, pill, detail in rows
    )
    return (
        "<h2>Server health</h2>"
        f"<table><thead><tr>"
        f"<th>Component</th><th>Status</th><th>Detail</th>"
        f"</tr></thead><tbody>{body}</tbody></table>"
    )


def _ok_pill(value: Any) -> str:
    """green ok / red missing pill — green for truthy, red for
    falsy. Unknown (None) renders as a gray dash."""
    if value is None:
        return "<span class='pill dim'>—</span>"
    if value:
        return "<span class='pill ok'>OK</span>"
    return "<span class='pill err'>MISSING</span>"


def _warn_pill(value: Any) -> str:
    """yellow warn / gray idle — used for transient state like
    "install running"."""
    if value:
        return "<span class='pill warn'>active</span>"
    return "<span class='pill dim'>idle</span>"


# ───── TOOLS ────────────────────────────────────────────────────────


_TOOLS_ORDER = (
    "ip", "ethtool", "lldpcli", "lspci",
    "ibv_devinfo", "perftest", "dpdk_devbind",
)


def _render_tools_section(snapshot: Dict[str, Any]) -> str:
    health = snapshot.get("health") or {}
    tools = health.get("tools_present") or {}
    if not tools:
        return ""
    cells = "".join(
        f"<tr><td>{escape(name)}</td>"
        f"<td>{_ok_pill(bool(tools.get(name)))}</td></tr>"
        for name in _TOOLS_ORDER
    )
    return (
        "<h2>CLI tools present</h2>"
        f"<table><thead><tr>"
        f"<th>Tool</th><th>Status</th>"
        f"</tr></thead><tbody>{cells}</tbody></table>"
    )


# ───── HUGEPAGES ────────────────────────────────────────────────────


def _render_hugepages_section(snapshot: Dict[str, Any]) -> str:
    health = snapshot.get("health") or {}
    hp = health.get("hugepages") or {}
    by_node = hp.get("by_node") or []
    if not by_node and not hp:
        return ""
    if not by_node:
        # Older /api/admin/health surfaced a single global count;
        # render it as a one-row table for visual consistency.
        body = (
            f"<tr><td>—</td>"
            f"<td class='num'>{hp.get('nr_hugepages') or 0}</td>"
            f"<td class='num'>{hp.get('free_hugepages') or 0}</td>"
            f"<td class='code'>"
            f"{escape(str(hp.get('size_kb') or '—'))} kB"
            f"</td></tr>"
        )
    else:
        body = "".join(
            f"<tr><td>node {escape(str(n.get('node')))}</td>"
            f"<td class='num'>{escape(str(n.get('nr_hugepages') or 0))}</td>"
            f"<td class='num'>{escape(str(n.get('free_hugepages') or 0))}</td>"
            f"<td class='code'>"
            f"{escape(str(n.get('size_kb') or '—'))} kB"
            f"</td></tr>"
            for n in by_node
        )
    return (
        "<h2>Hugepages</h2>"
        f"<table><thead><tr>"
        f"<th>NUMA</th>"
        f"<th class='num'>Total</th>"
        f"<th class='num'>Free</th>"
        f"<th>Page size</th>"
        f"</tr></thead><tbody>{body}</tbody></table>"
    )


# ───── INTERFACES ───────────────────────────────────────────────────


_IFACE_HEADERS = (
    "Iface", "Driver", "MAC", "IPv4", "Speed", "MTU",
    "Link", "NUMA", "PCIe", "Model",
)


def _render_interfaces_section(snapshot: Dict[str, Any]) -> str:
    interfaces = snapshot.get("interfaces") or []
    if not interfaces:
        return (
            "<h2>Network interfaces</h2>"
            "<p class='empty'>No interface data returned.</p>"
        )
    header = "".join(f"<th>{h}</th>" for h in _IFACE_HEADERS)
    body = "".join(_render_iface_row(i) for i in interfaces)
    return (
        "<h2>Network interfaces</h2>"
        f"<table><thead><tr>{header}</tr></thead>"
        f"<tbody>{body}</tbody></table>"
    )


def _render_iface_row(i: Dict[str, Any]) -> str:
    name = i.get("name") or i.get("iface") or "?"
    driver = i.get("driver") or "—"
    mac = i.get("mac") or i.get("mac_address") or "—"
    ipv4 = _first_ipv4(i)
    speed = i.get("speed")
    speed_txt = (f"{speed} Mb/s" if isinstance(speed, int) and speed > 0
                 else "—")
    mtu = i.get("mtu")
    mtu_txt = f"{mtu}" if isinstance(mtu, int) and mtu > 0 else "—"
    link = (i.get("operstate") or i.get("state") or "—").lower()
    link_html = _link_badge(link)
    numa = i.get("numa_node")
    numa_txt = f"node {numa}" if isinstance(numa, int) and numa >= 0 \
        else "—"
    pcie = _pcie_text(i)
    pcie_warn = " pcie-warn" if i.get("pcie_downgraded") else ""
    model = i.get("nic_model") or "—"
    return (
        f"<tr>"
        f"<td class='code'>{escape(str(name))}</td>"
        f"<td class='code'>{escape(str(driver))}</td>"
        f"<td class='code'>{escape(str(mac))}</td>"
        f"<td class='code'>{escape(ipv4)}</td>"
        f"<td class='code'>{escape(speed_txt)}</td>"
        f"<td class='code'>{escape(mtu_txt)}</td>"
        f"<td>{link_html}</td>"
        f"<td class='code'>{escape(numa_txt)}</td>"
        f"<td class='code{pcie_warn}'>{escape(pcie)}</td>"
        f"<td>{escape(str(model))}</td>"
        f"</tr>"
    )


def _link_badge(link: str) -> str:
    if link in ("up", "active"):
        return "<span class='pill ok'>UP</span>"
    if link in ("down", "no-carrier"):
        return "<span class='pill err'>DOWN</span>"
    if link in ("dormant", "lowerlayerdown", "unknown"):
        return "<span class='pill warn'>" + escape(link.upper()) + "</span>"
    return escape(link) if link else "—"


def _pcie_text(d: Dict[str, Any]) -> str:
    gen = d.get("pcie_gen")
    width = d.get("pcie_current_width") or d.get("pcie_width")
    if not gen and not width:
        return "—"
    cur = f"Gen{gen}" if gen else "Gen?"
    if width:
        cur += f" x{width}"
    return cur


def _first_ipv4(i: Dict[str, Any]) -> str:
    # Try several plausible shapes — the /api/interfaces payload
    # varies across server versions.
    ip = i.get("ipv4") or i.get("ip") or i.get("address")
    if isinstance(ip, str) and "." in ip:
        return ip
    ips = i.get("ips") or i.get("addresses") or []
    if isinstance(ips, list):
        for entry in ips:
            if isinstance(entry, str) and "." in entry:
                return entry
            if isinstance(entry, dict):
                v = entry.get("ip") or entry.get("address") or ""
                if "." in v:
                    return v
    return "—"


# ───── RDMA HCAs ────────────────────────────────────────────────────


_RDMA_HEADERS = (
    "HCA", "Model", "Driver", "Vendor", "FW",
    "Link", "Rate", "MTU", "State",
    "NUMA", "PCIe", "NetDev", "IPv4", "GID",
)


def _render_rdma_section(snapshot: Dict[str, Any]) -> str:
    devices = snapshot.get("rdma_devices") or []
    if not devices:
        return (
            "<h2>RDMA HCAs</h2>"
            "<p class='empty'>No RDMA devices detected. The kernel "
            "may not have RDMA support loaded, or the host has no "
            "HCAs.</p>"
        )
    header = "".join(f"<th>{h}</th>" for h in _RDMA_HEADERS)
    body = "".join(_render_hca_row(d) for d in devices)
    return (
        "<h2>RDMA HCAs</h2>"
        f"<table><thead><tr>{header}</tr></thead>"
        f"<tbody>{body}</tbody></table>"
    )


def _render_hca_row(d: Dict[str, Any]) -> str:
    hca = d.get("name") or "?"
    # Reuse the same NIC-model mapping the RDMA report uses.
    try:
        from utils.rdma_report import _resolve_nic_model
        model = _resolve_nic_model(d.get("vendor"))
    except Exception:
        model = "—"
    driver = d.get("driver") or "—"
    vendor = d.get("vendor") or "—"
    fw = d.get("fw_version") or "—"
    ports = d.get("ports") or []
    port = ports[0] if ports and isinstance(ports[0], dict) else {}
    link = port.get("link_layer") or "—"
    rate = (port.get("rate") or "")
    # Strip "(4X HDR)" classifier for readability.
    if rate and "(" in rate:
        rate = rate.split("(", 1)[0].strip()
    if not rate:
        rate = "—"
    mtu = port.get("mtu")
    mtu_txt = f"{mtu} B" if isinstance(mtu, int) and mtu > 0 else "—"
    state = (port.get("state") or "—").upper()
    state_html = (
        f"<span class='pill {'ok' if state == 'ACTIVE' else 'err'}'>"
        f"{escape(state)}</span>"
        if state != "—" else "—"
    )
    numa = d.get("numa_node")
    numa_txt = f"node {numa}" if isinstance(numa, int) else "—"
    pcie = _pcie_text(d)
    pcie_warn = " pcie-warn" if d.get("pcie_downgraded") else ""
    net = "+".join(d.get("net_ifaces") or []) or "—"
    ips_by_iface = d.get("netdev_ips") or {}
    ipv4 = "—"
    for _, lst in ips_by_iface.items():
        for v in lst:
            if "." in v.split("/", 1)[0]:
                ipv4 = v
                break
        if ipv4 != "—":
            break
    gids = port.get("gids") or []
    gid = gids[0] if gids else "—"
    if len(gid) > 24:
        gid = gid[:19] + "…"
    return (
        f"<tr>"
        f"<td class='code'>{escape(str(hca))}</td>"
        f"<td>{escape(model)}</td>"
        f"<td class='code'>{escape(driver)}</td>"
        f"<td class='code'>{escape(vendor)}</td>"
        f"<td class='code'>{escape(fw)}</td>"
        f"<td class='code'>{escape(link)}</td>"
        f"<td class='code'>{escape(rate)}</td>"
        f"<td class='code'>{escape(mtu_txt)}</td>"
        f"<td>{state_html}</td>"
        f"<td class='code'>{escape(numa_txt)}</td>"
        f"<td class='code{pcie_warn}'>{escape(pcie)}</td>"
        f"<td class='code'>{escape(net)}</td>"
        f"<td class='code'>{escape(ipv4)}</td>"
        f"<td class='code'>{escape(gid)}</td>"
        f"</tr>"
    )


# ───── BIND HISTORY ─────────────────────────────────────────────────


def _render_bind_history_section(snapshot: Dict[str, Any]) -> str:
    history = snapshot.get("bind_history") or []
    if not history:
        return ""
    header = (
        "<th>Timestamp</th><th>PCI BDF</th>"
        "<th>From driver</th><th>To driver</th>"
        "<th>Action</th>"
    )
    body = "".join(
        f"<tr><td class='code'>"
        f"{escape(str(h.get('timestamp') or '—'))}</td>"
        f"<td class='code'>{escape(str(h.get('pci') or '—'))}</td>"
        f"<td class='code'>"
        f"{escape(str(h.get('from_driver') or '—'))}</td>"
        f"<td class='code'>"
        f"{escape(str(h.get('to_driver') or '—'))}</td>"
        f"<td class='code'>"
        f"{escape(str(h.get('action') or '—'))}</td></tr>"
        for h in history[-40:]
    )
    return (
        "<h2>DPDK bind history (last 40)</h2>"
        f"<table><thead><tr>{header}</tr></thead>"
        f"<tbody>{body}</tbody></table>"
    )


# ───── ORPHANS ──────────────────────────────────────────────────────


def _render_orphans_section(snapshot: Dict[str, Any]) -> str:
    orphans = snapshot.get("orphans") or []
    if not orphans:
        return ""
    header = (
        "<th>PID</th><th>Role</th><th>Stream-id</th>"
        "<th>BDF</th><th>Elapsed</th><th>Cmdline</th>"
    )
    body = "".join(
        f"<tr><td class='code'>{escape(str(o.get('pid') or '—'))}</td>"
        f"<td class='code'>{escape(str(o.get('role') or '—'))}</td>"
        f"<td class='code'>"
        f"{escape(_short(o.get('stream_id') or '—', 20))}</td>"
        f"<td class='code'>{escape(str(o.get('bdf') or '—'))}</td>"
        f"<td class='code'>"
        f"{_etime_txt(o.get('etime_seconds'))}</td>"
        f"<td class='code dim'>"
        f"{escape(_short(o.get('cmdline') or '', 160))}</td></tr>"
        for o in orphans
    )
    return (
        "<h2><span class='pill err'>🧟 Orphan workers</span></h2>"
        "<p class='meta'>Untracked tx/rx_worker processes — these "
        "leak CPU + PCIe on their NIC. Use the GUI's Stop All "
        "or POST /api/streams/orphans/reap to clear.</p>"
        f"<table><thead><tr>{header}</tr></thead>"
        f"<tbody>{body}</tbody></table>"
    )


# ───── helpers ──────────────────────────────────────────────────────


def _short(s: Any, n: int) -> str:
    """Truncate a string for table cells. Returns "—" for empty."""
    if s is None:
        return "—"
    s = str(s)
    return s if len(s) <= n else s[: n - 1] + "…"


def _etime_txt(seconds: Any) -> str:
    if not isinstance(seconds, int):
        return "?"
    if seconds < 60:
        return f"{seconds}s"
    if seconds < 3600:
        return f"{seconds // 60}m{seconds % 60}s"
    return f"{seconds // 3600}h{(seconds % 3600) // 60}m"
