"""v0.5.163: shared HTML-report builder for the Blast + Topology
RDMA dialogs.

Operator: "also allow user to generate report for this test both
in via blast test and topology test" — HTML format, scope = all
runs since the dialog opened (append-only session log).

v0.5.167 redesign: operator flagged the prior report as low-info
and hard to scan. Three fixes:

1. **Endpoint details** — each run now carries a per-side device
   dump (NIC vendor / model / driver / link rate / MTU / FW /
   GIDs / netdevs), rendered as a small table.
2. **Key result callout** — the BW headline is pulled to the
   top of each run-card so the operator doesn't have to scroll
   to the Results table.
3. **Visibility pass** — paired param table (the old grid was
   spreading dt/dd as independent cells, so labels and values
   interleaved); zebra-stripe tables; left-stripe on the run
   card; clearer hierarchy.

Each dialog maintains a `_run_log: List[Dict]` instance var.
Every completed run (single iteration or one bulk iterate-N
session) appends a dict with the metadata + per-row results.
The Export button passes that list here.

Schema for one run entry:

  {
    "kind":          "blast" | "topology",
    "started_at":    ISO string (operator-provided wall-clock),
    "test":          "ib_send_bw" | ... ,
    "params":        {msg_size, qp_count, mtu, tx_depth, gid_index,
                      bidirectional, cpu_util, parallel_workers,
                      iterations, shape (topology only)},
    "endpoints":     {server: "<host> <hca>", client: "..."} or
                     {pairs: [{idx, server, client}, ...]}
    "endpoint_details":  # v0.5.167 — optional
                     [{side, tg, hca, device: {...payload from
                       /api/rdma/devices...}, pair_index?}, ...]
    "rows":          [{label, bw_gbps, msgrate_mpps, lat_avg_us,
                       state}, ...]
    "summary":       {bw_avg, bw_min, bw_max, msgrate_avg, ...} |
                     None
  }

The HTML is self-contained (inline CSS), no external assets.
Operators can email / archive the file as-is.
"""
from __future__ import annotations

import re
from html import escape
from typing import Any, Dict, List, Optional


# v0.5.167: human-readable param labels. Falls through to the raw
# key when not in the map — so brand-new params show up without
# code changes here, just less polished.
_PARAM_LABELS: Dict[str, str] = {
    "test": "Test",
    "msg_size": "Message size",
    "qp_count": "QP count",
    "duration_s": "Duration",
    "tx_depth": "TX depth",
    "gid_index": "GID index",
    "mtu": "MTU",
    "bidirectional": "Bidirectional",
    "cpu_util": "CPU util reporting",
    "parallel_workers": "Parallel workers",
    "iterations": "Iterations",
    "shape": "Topology shape",
    "base_port": "Base port",
}


_PARAM_UNITS: Dict[str, str] = {
    "msg_size": "B",
    "duration_s": "s",
}


def build_html_report(
    *,
    title: str,
    runs: List[Dict[str, Any]],
    generated_at: str,
    client_version: Optional[str] = None,
) -> str:
    """Render the full HTML document. `runs` is the append-only
    session log (oldest first). `generated_at` is the operator-
    side wall-clock at export time (the dialog passes this in so
    the function stays pure / testable)."""
    head = _render_head(title)
    intro = _render_intro(title, generated_at, len(runs), client_version)
    body = "".join(_render_run_section(i, r) for i, r in enumerate(runs))
    if not runs:
        body = (
            "<p class='empty'>No runs recorded yet. Run a test and "
            "click Export Report again.</p>"
        )
    footer = (
        "<footer>Generated by netgen RDMA dialogs. "
        "Self-contained HTML — safe to archive or email.</footer>"
    )
    return (
        f"<!DOCTYPE html>\n<html lang='en'><head>{head}</head>"
        f"<body><main class='container'>{intro}{body}{footer}</main>"
        f"</body></html>"
    )


# ───── HEAD / INTRO ────────────────────────────────────────────────────


def _render_head(title: str) -> str:
    css = """
        :root {
          --fg: #0f172a; --muted: #475569; --line: #cbd5e1;
          --card: #f8fafc; --accent: #1d4ed8;
          --warn: #b45309; --ok: #047857; --err: #b91c1c;
          --stripe: #f1f5f9; --headline: #064e3b; --headline-bg: #ecfdf5;
          --pill-bg: #e0e7ff; --kv-label: #475569;
        }
        * { box-sizing: border-box; }
        body {
          font-family: -apple-system, BlinkMacSystemFont, "Segoe UI",
                       Roboto, sans-serif;
          color: var(--fg); background: #fff; margin: 0;
          line-height: 1.5;
        }
        .container { max-width: 1180px; margin: 0 auto; padding: 24px; }
        h1 { font-size: 22px; margin: 0 0 4px; }
        h2 {
          font-size: 17px; margin: 0 0 4px;
        }
        h3 {
          font-size: 12px; margin: 18px 0 6px; color: var(--muted);
          text-transform: uppercase; letter-spacing: 0.5px;
          font-weight: 700;
        }
        .meta { color: var(--muted); font-size: 12px; margin-bottom: 16px; }
        .meta strong { color: var(--fg); font-weight: 600; }
        .empty {
          padding: 16px; background: var(--card); border-radius: 6px;
          color: var(--muted); font-style: italic;
        }
        /* Run card with left accent stripe — operators scanning
           a multi-run report need a clear visual divider per run. */
        .run-card {
          background: var(--card);
          border: 1px solid var(--line); border-left: 4px solid var(--accent);
          border-radius: 6px; padding: 16px 18px; margin-bottom: 18px;
        }
        .run-head {
          display: flex; align-items: baseline; gap: 10px;
          flex-wrap: wrap;
        }
        .run-head .timestamp {
          color: var(--muted); font-size: 12px;
        }
        /* The big-number headline — operators read this first and
           often stop here. Mirrors the in-app post-run card. */
        .headline {
          margin-top: 10px; padding: 8px 12px;
          background: var(--headline-bg);
          border: 1px solid #10b981; border-radius: 4px;
          color: var(--headline);
        }
        .headline .num { font-size: 22px; font-weight: 700; }
        .headline .num.mr { font-size: 16px; }
        .headline .unit { font-size: 11px; color: #065f46; }
        .headline .tail { font-size: 11px; color: #047857; margin-left: 4px; }
        .headline .sep { color: #475569; padding: 0 4px; }
        /* Param table — two columns of {label, value} pairs.
           Earlier versions used a `display: grid` over <dt>/<dd>
           which spread labels and values into independent cells,
           interleaving them. The <table> + paired rows fix is
           verbose-source but bullet-proof. */
        table.params, table.endpoints, table.results {
          width: 100%; border-collapse: collapse; font-size: 12px;
          margin-top: 6px;
        }
        table.params td {
          padding: 4px 10px;
          border-bottom: 1px solid var(--line);
          vertical-align: top;
        }
        table.params td.k {
          color: var(--kv-label); font-weight: 500; width: 28%;
        }
        table.params td.v {
          font-family: "SF Mono", Menlo, Consolas, monospace;
        }
        table.endpoints th, table.endpoints td,
        table.results th, table.results td {
          padding: 6px 10px; text-align: left;
          border-bottom: 1px solid var(--line);
        }
        table.endpoints th, table.results th {
          color: var(--muted); font-weight: 600;
          background: #eef2f7; font-size: 11px;
          text-transform: uppercase; letter-spacing: 0.3px;
        }
        table.endpoints tbody tr:nth-child(even),
        table.results tbody tr:nth-child(even) {
          background: var(--stripe);
        }
        table.endpoints td.code, table.endpoints td.dim {
          font-family: "SF Mono", Menlo, Consolas, monospace;
          font-size: 11px;
        }
        table.endpoints td.dim { color: var(--muted); }
        table.endpoints td.side-srv { color: var(--accent); font-weight: 600; }
        table.endpoints td.side-cli { color: var(--ok); font-weight: 600; }
        td.num {
          font-family: "SF Mono", Menlo, Consolas, monospace;
          text-align: right;
        }
        tr.summary { background: #eef2ff !important; font-weight: 600; }
        tr.summary td { border-top: 2px solid var(--accent); }
        .pill {
          display: inline-block; padding: 1px 8px; border-radius: 10px;
          font-size: 11px; background: var(--pill-bg); color: var(--accent);
          text-transform: lowercase;
        }
        .badge-link, .badge-state {
          display: inline-block; padding: 1px 6px; border-radius: 3px;
          font-size: 10px; font-weight: 600; letter-spacing: 0.3px;
        }
        .badge-link {
          background: #dbeafe; color: var(--accent);
          text-transform: uppercase;
        }
        .badge-state.up { background: #d1fae5; color: var(--ok); }
        .badge-state.down { background: #fee2e2; color: var(--err); }
        .badge-state.init { background: #fef3c7; color: var(--warn); }
        /* v0.5.170: PCIe downgrade warning — operator-critical
           signal. Yellow background draws the eye without
           screaming red (the link is working, just not at full
           capability). */
        .pcie-warn {
          background: #fef3c7;
          color: var(--warn);
          font-weight: 600;
        }
        /* v0.5.172: horizontal scroll for the endpoint table
           when the 16 columns don't fit the run-card width. The
           wrapper keeps the run-card border tidy and the table
           pans within it instead of spilling. The native
           browser scrollbar appears only when needed. */
        .endpoint-scroll {
          overflow-x: auto;
          max-width: 100%;
          margin-top: 6px;
        }
        .endpoint-scroll table.endpoints {
          margin-top: 0;
          min-width: max-content;
        }
        footer { color: var(--muted); font-size: 11px; margin-top: 32px;
          padding-top: 12px; border-top: 1px solid var(--line);
        }
    """
    return (
        f"<meta charset='utf-8'>"
        f"<title>{escape(title)}</title>"
        f"<style>{css}</style>"
    )


def _render_intro(
    title: str, generated_at: str, n_runs: int,
    client_version: Optional[str],
) -> str:
    ver = (
        f" &middot; netgen {escape(client_version)}"
        if client_version else ""
    )
    return (
        f"<h1>{escape(title)}</h1>"
        f"<div class='meta'>"
        f"<strong>Generated:</strong> {escape(generated_at)}{ver}"
        f" &middot; <strong>{n_runs} run"
        f"{'s' if n_runs != 1 else ''}</strong>"
        f"</div>"
    )


# ───── PER-RUN SECTION ─────────────────────────────────────────────────


def _render_run_section(idx: int, run: Dict[str, Any]) -> str:
    head = (
        f"<div class='run-head'>"
        f"<h2>Run #{idx + 1}"
        f" &middot; <span class='pill'>{escape(run.get('kind') or '?')}</span>"
        f" &middot; {escape(run.get('test') or '?')}</h2>"
        f"<span class='timestamp'>started at "
        f"{escape(run.get('started_at') or '?')}</span>"
        f"</div>"
    )
    headline = _render_headline(run)
    params = _render_params(run.get("params") or {})
    endpoints = _render_endpoints(
        run.get("endpoints") or {},
        run.get("endpoint_details") or [],
    )
    rows = _render_rows_table(
        run.get("rows") or [],
        run.get("summary") or None,
    )
    # v0.5.177: RFC 2544-style latency-vs-size curve. Appended when
    # the run carries `lat_sweep` (Spirent/Ixia-style). Empty string
    # for single-size runs so the legacy layout is unchanged.
    sweep_section = _render_lat_sweep_section(
        run.get("lat_sweep") or [],
        run.get("params") or {},
    )
    return (
        f"<section class='run-card'>"
        f"{head}{headline}"
        f"<h3>Parameters</h3>{params}"
        f"<h3>Endpoints</h3>{endpoints}"
        f"<h3>Results</h3>{rows}"
        f"{sweep_section}"
        f"</section>"
    )


_RATE_RE = re.compile(r"([0-9]+(?:\.[0-9]+)?)\s*Gb/sec",
                       re.IGNORECASE)


def _extract_line_rate_gbps(run: Dict[str, Any]) -> Optional[float]:
    """v0.5.170: pull a line-rate number from the endpoint details
    so we can show `BW / line-rate %` in the headline. Uses the
    SLOWEST endpoint as the cap — a 200 G ↔ 100 G run is capped
    at 100 G end-to-end. Returns None when we can't parse any
    endpoint's rate (legacy run_log entries without details)."""
    details = run.get("endpoint_details") or []
    rates: List[float] = []
    for d in details:
        dev = d.get("device") or {}
        ports = dev.get("ports") or []
        for p in ports:
            r = (p.get("rate") or "")
            m = _RATE_RE.search(r)
            if m:
                try:
                    rates.append(float(m.group(1)))
                    break
                except ValueError:
                    pass
    return min(rates) if rates else None


def _render_headline(run: Dict[str, Any]) -> str:
    """v0.5.167: key-result callout at the top of the run card.
    Pulls the headline BW + MsgRate from `summary` (or the lone
    `rows` entry for one-shot runs). Mirrors the dialog's post-run
    card so the export carries the same first-glance number.

    v0.5.170: appends `· X% of N G` line-rate efficiency when the
    endpoint table can supply a rate. Lets operators tell at a
    glance whether the test hit line rate (>90% = good).

    v0.5.180 (re-audit H-RE-3): dispatch on summary/row shape.
    Pre-fix this always rendered the BW headline; lat runs
    showed "— Gbps | — Mpps" in the green callout box despite
    the per-row table (in `_render_rows_table`) correctly
    dispatching to lat columns. The v0.5.179 fix landed the row
    dispatch but never updated the headline.
    """
    summary = run.get("summary") or {}
    rows = run.get("rows") or []
    # v0.5.180: lat vs BW dispatch — match `_render_rows_table`'s
    # `has_lat` predicate so the headline can't disagree with
    # the table below it.
    has_lat = (
        isinstance(summary.get("lat_avg_us"), (int, float))
        or any(isinstance(r.get("lat_avg_us"), (int, float))
               for r in rows)
    )
    if has_lat:
        return _render_lat_headline(run, summary, rows)

    # v0.5.181 followup: headline label reflects aggregation mode.
    # `sum_workers` / `sum_pairs` → "total across N", `avg_iterations`
    # → "average across N samples".
    mode = summary.get("aggregation_mode") or "avg_iterations"
    is_sum = mode in ("sum_workers", "sum_pairs")
    if (isinstance(summary.get("bw_avg_gbps"), (int, float))
            and summary.get("samples", 0) > 1):
        bw = float(summary["bw_avg_gbps"])
        n = int(summary["samples"])
        # v0.5.181 G-4: pairs_attempted is the sibling for the
        # sum_pairs mode (Topology) — same "N of M reported" honesty.
        if mode == "sum_pairs":
            attempted = summary.get("pairs_attempted")
        else:
            attempted = summary.get("workers_attempted")
        if is_sum:
            unit = ("workers" if mode == "sum_workers" else "pairs")
            if (isinstance(attempted, int) and attempted
                    and n < attempted):
                tail = f"total across {n} of {attempted} {unit}"
            else:
                tail = f"total across {n} {unit}"
        else:
            tail = f"average across {n} samples"
    else:
        bws = [r["bw_gbps"] for r in rows
               if isinstance(r.get("bw_gbps"), (int, float))]
        bw = max(bws) if bws else None
        # v0.5.182 NB-11: single-sample sum_workers / sum_pairs runs
        # (e.g. a 1-parallel-worker BW test) read `total X · final` —
        # inconsistent with the multi-worker phrase. Say
        # "total across 1 worker / pair" instead so the language
        # matches across worker counts.
        if is_sum and summary.get("samples") == 1:
            unit = ("worker" if mode == "sum_workers" else "pair")
            tail = f"total across 1 {unit}"
        else:
            tail = "final"
    if isinstance(summary.get("msgrate_avg_mpps"), (int, float)):
        mr: Optional[float] = float(summary["msgrate_avg_mpps"])
    else:
        mrs = [r["msgrate_mpps"] for r in rows
               if isinstance(r.get("msgrate_mpps"), (int, float))]
        mr = mrs[-1] if mrs else None
    if bw is None and mr is None:
        return ""
    bw_txt = f"{bw:.2f}" if isinstance(bw, float) else "—"
    mr_txt = f"{mr:.4f}" if isinstance(mr, float) else "—"
    extras = []
    if isinstance(summary.get("bw_min_gbps"), (int, float)) \
            and isinstance(summary.get("bw_max_gbps"), (int, float)) \
            and summary.get("samples", 0) > 1:
        extras.append(
            f"min {summary['bw_min_gbps']:.2f} / "
            f"max {summary['bw_max_gbps']:.2f} Gbps"
        )
    # v0.5.170: line-rate efficiency. Operators ask this every
    # run: "did we hit line rate?" Show the % up front.
    # v0.5.180 (re-audit M-RE-2): gate on `bw is float`. The lat
    # branch above already returns; the residual safety here is
    # for runs where `_render_headline` somehow ends up here with
    # neither bw nor lat data, where bw stays None and the calc
    # would multiply None.
    line_rate = _extract_line_rate_gbps(run)
    if isinstance(bw, float) and line_rate and line_rate > 0:
        pct = (bw / line_rate) * 100.0
        extras.append(
            f"{pct:.1f}% of {line_rate:g} G line rate")
    tail_html = escape(tail)
    if extras:
        tail_html += " &middot; " + " &middot; ".join(escape(b) for b in extras)
    return (
        f"<div class='headline'>"
        f"<span class='num'>{bw_txt}</span>"
        f"<span class='unit'> Gbps</span>"
        f"<span class='sep'>|</span>"
        f"<span class='num mr'>{mr_txt}</span>"
        f"<span class='unit'> Mpps</span>"
        f"<span class='tail'>&middot; {tail_html}</span>"
        f"</div>"
    )


def _render_lat_headline(
    run: Dict[str, Any],
    summary: Dict[str, Any],
    rows: List[Dict[str, Any]],
) -> str:
    """v0.5.180 (re-audit H-RE-3): latency-flavoured headline.
    Mirrors the BW headline's shape — same green callout box,
    same `<span class='num'>` styling — so the report's visual
    rhythm is uniform across BW and lat runs. The unit just
    swaps from Gbps/Mpps to µs avg / µs p99.

    Line-rate efficiency calc is SKIPPED for lat runs: a `% of
    line rate` number against a latency µs value is meaningless
    (lat tests intentionally don't fill the wire)."""
    # v0.5.182 NB-3: surface "X of N workers" honesty when a
    # multi-worker lat run had partial reporting (operator's srv06
    # send_lat showed 1 of 16 workers done; tail used to say
    # `final` masking the gap).
    mode = summary.get("aggregation_mode") or ""
    if mode == "sum_pairs":
        attempted = summary.get("pairs_attempted")
        unit = "pairs"
    else:
        attempted = summary.get("workers_attempted")
        unit = "workers"
    if (isinstance(summary.get("lat_avg_us"), (int, float))
            and summary.get("samples", 0) > 1):
        avg_us = float(summary["lat_avg_us"])
        n = int(summary["samples"])
        if (isinstance(attempted, int) and attempted
                and n < attempted):
            tail = f"average across {n} of {attempted} {unit}"
        else:
            tail = f"average across {n} samples"
    else:
        lats = [r["lat_avg_us"] for r in rows
                if isinstance(r.get("lat_avg_us"), (int, float))]
        avg_us = lats[-1] if lats else None
        if (isinstance(attempted, int) and attempted
                and len(lats) < attempted):
            tail = f"{len(lats)} of {attempted} {unit} reported"
        else:
            tail = "final"
    p99_rows = [r.get("lat_p99_us") for r in rows
                if isinstance(r.get("lat_p99_us"), (int, float))]
    p99_us = p99_rows[-1] if p99_rows else None
    if avg_us is None and p99_us is None:
        return ""
    avg_txt = (f"{avg_us:.2f}" if isinstance(avg_us, float)
               else "—")
    p99_txt = (f"{p99_us:.2f}" if isinstance(p99_us, float)
               else "—")
    extras = []
    if (isinstance(summary.get("lat_min_us"), (int, float))
            and isinstance(summary.get("lat_max_us"), (int, float))
            and summary.get("samples", 0) > 1):
        extras.append(
            f"min {summary['lat_min_us']:.2f} / "
            f"max {summary['lat_max_us']:.2f} µs")
    tail_html = escape(tail)
    if extras:
        tail_html += (" &middot; "
                      + " &middot; ".join(escape(b) for b in extras))
    return (
        f"<div class='headline'>"
        f"<span class='num'>{avg_txt}</span>"
        f"<span class='unit'> µs avg</span>"
        f"<span class='sep'>|</span>"
        f"<span class='num mr'>{p99_txt}</span>"
        f"<span class='unit'> µs p99</span>"
        f"<span class='tail'>&middot; {tail_html}</span>"
        f"</div>"
    )


def _render_params(params: Dict[str, Any]) -> str:
    """v0.5.167: paired-row table instead of dl/dt/dd grid.

    The old `display: grid; grid-template-columns: auto-fill` over
    dt/dd treated each <dt> and <dd> as an independent cell, so
    labels and values interleaved when the column count didn't
    line up. A <table> with one row per pair eliminates the bug
    and keeps the report readable on narrow viewports."""
    if not params:
        return "<p class='meta'>—</p>"
    rows = []
    for k, v in params.items():
        label = _PARAM_LABELS.get(str(k), str(k))
        v_str = _format_param_value(k, v)
        rows.append(
            f"<tr><td class='k'>{escape(label)}</td>"
            f"<td class='v'>{escape(v_str)}</td></tr>"
        )
    return f"<table class='params'><tbody>{''.join(rows)}</tbody></table>"


def _format_param_value(key: str, value: Any) -> str:
    if isinstance(value, bool):
        return "yes" if value else "no"
    unit = _PARAM_UNITS.get(str(key), "")
    return f"{value}{(' ' + unit) if unit else ''}"


# ───── ENDPOINTS ───────────────────────────────────────────────────────


_ENDPOINT_HEADERS = (
    "Side", "TG", "HCA", "Model", "Link", "Rate", "MTU", "State",
    "PCIe", "NUMA", "NetDev", "IPv4", "Driver", "Vendor", "FW",
    "GID",
)


# v0.5.170: Mellanox board_id → friendly product name. Operators
# read "ConnectX-7" not "MT_0000000838". Mirrors the mapping the
# admin console uses (v0.5.73). Falls through to the raw board_id
# when unknown — adding a missing prefix later is a one-line
# diff. The mapping is *prefix*-based; revisions append digits
# but the first 4-6 hex digits identify the product family.
_BOARD_ID_TO_MODEL = {
    "MT_0000000200": "ConnectX-3 Pro",
    "MT_0000000225": "ConnectX-6",   # v0.5.172: FW 20.40.x
                                       # family seen on srv02 lab
                                       # boxes; operator-reported
                                       # board_id was rendering as
                                       # `—` despite the HCA being
                                       # a known ConnectX-6 part.
    "MT_0000000418": "ConnectX-5",
    "MT_0000000414": "ConnectX-5",
    "MT_0000000437": "ConnectX-6",
    "MT_0000000591": "ConnectX-6 Dx",
    "MT_0000000610": "ConnectX-6 Lx",
    "MT_0000000838": "ConnectX-7",
    "MT_0000000883": "ConnectX-7",
    "MT_0000001019": "ConnectX-8",
    # Broadcom (Thor / Thor2)
    "BCM5755X": "BCM Thor",
    "BCM5760X": "BCM Thor2",
    # AMD Pollara
    "ATI0001":   "Pollara 400",
}


def _resolve_nic_model(vendor: Optional[str]) -> str:
    """Return a friendly product name for the HCA, or `—` when we
    don't recognise the board_id. The mapping is prefix-based so
    future revisions of an existing product still match."""
    if not vendor:
        return "—"
    v = str(vendor).strip().upper()
    # Exact match first.
    if v in _BOARD_ID_TO_MODEL:
        return _BOARD_ID_TO_MODEL[v]
    # Prefix match — board_ids sometimes append a revision suffix.
    for key, model in _BOARD_ID_TO_MODEL.items():
        if v.startswith(key):
            return model
    return "—"


def _format_pcie_cell(dev: Dict[str, Any]) -> str:
    """`Gen4 x16` or `Gen4 x16 (max Gen5 x16)` when downgraded.
    `—` when the HCA didn't report PCIe info."""
    gen = dev.get("pcie_gen")
    width = dev.get("pcie_current_width")
    if not gen and not width:
        return "—"
    cur = f"Gen{gen}" if gen else "Gen?"
    if width:
        cur += f" x{width}"
    if dev.get("pcie_downgraded"):
        max_gen = dev.get("pcie_max_gen")
        max_w = dev.get("pcie_max_width")
        cap_bits = []
        if max_gen:
            cap_bits.append(f"Gen{max_gen}")
        if max_w:
            cap_bits.append(f"x{max_w}")
        if cap_bits:
            cur += f" (max {' '.join(cap_bits)})"
    return cur


def _format_pcie_badge_class(dev: Dict[str, Any]) -> str:
    """CSS class for the PCIe cell — `pcie-warn` when downgraded
    so the operator's eye snaps to it."""
    return "pcie-warn" if dev.get("pcie_downgraded") else ""


def _format_ipv4_cell(dev: Dict[str, Any]) -> str:
    """Pick the first IPv4 across the HCA's netdevs. Most HCAs
    expose one netdev; bonded HCAs expose multiple — we show
    only the first to keep the column narrow. The remaining IPs
    are still in the JSON payload for power users."""
    ips_by_iface = dev.get("netdev_ips") or {}
    for iface, ip_list in ips_by_iface.items():
        for ip in ip_list:
            if "." in ip.split("/", 1)[0]:
                return ip
    return "—"


def _format_numa_cell(dev: Dict[str, Any]) -> str:
    n = dev.get("numa_node")
    return f"node {n}" if isinstance(n, int) else "—"


def _render_endpoints(
    eps: Dict[str, Any],
    details: List[Dict[str, Any]],
) -> str:
    """v0.5.167: rich endpoint table when `endpoint_details` is
    present. Falls back to the legacy server/client string block
    or pairs list for back-compat (old run_log entries without
    rich data shouldn't crash the renderer)."""
    if details:
        return _render_endpoint_table(details)
    if "pairs" in eps:
        items = "".join(
            f"<li>#{escape(str(p.get('idx', '?')))} "
            f"<code>{escape(str(p.get('server', '?')))}</code> "
            f"&rarr; <code>{escape(str(p.get('client', '?')))}</code>"
            f"</li>"
            for p in eps.get("pairs") or []
        )
        return f"<ul>{items}</ul>" if items else "<p class='meta'>—</p>"
    server = eps.get("server")
    client = eps.get("client")
    if server or client:
        return (
            f"<p><strong>Server:</strong> "
            f"<code>{escape(str(server or '?'))}</code><br>"
            f"<strong>Client:</strong> "
            f"<code>{escape(str(client or '?'))}</code></p>"
        )
    return "<p class='meta'>—</p>"


def _render_endpoint_table(details: List[Dict[str, Any]]) -> str:
    if not details:
        return "<p class='meta'>—</p>"
    header = "".join(f"<th>{h}</th>" for h in _ENDPOINT_HEADERS)
    body = "".join(_render_endpoint_row(d) for d in details)
    # v0.5.172: wrap in overflow-x:auto. The endpoint table grew
    # to 16 columns (Side / TG / HCA / Model / Link / Rate / MTU
    # / State / PCIe / NUMA / NetDev / IPv4 / Driver / Vendor /
    # FW / GID) in v0.5.167+v0.5.170, which exceeds the run-card
    # max-width on most viewports. Without the wrapper, the
    # rightmost columns spilled outside the run-card border —
    # operator-reported.
    return (
        f"<div class='endpoint-scroll'>"
        f"<table class='endpoints'><thead><tr>{header}</tr></thead>"
        f"<tbody>{body}</tbody></table>"
        f"</div>"
    )


def _render_endpoint_row(d: Dict[str, Any]) -> str:
    side = (d.get("side") or "?").lower()
    side_css = f"side-{'srv' if side.startswith('s') else 'cli'}"
    side_disp = "server" if side.startswith("s") else "client"
    if d.get("pair_index") is not None:
        side_disp = f"#{d['pair_index']} {side_disp}"
    tg = d.get("tg") or ""
    hca = d.get("hca") or "?"
    dev = d.get("device") or {}
    port = _first_port(dev)
    link = port.get("link_layer") or "—"
    rate = _shorten_rate(port.get("rate"))
    mtu = port.get("mtu")
    mtu_txt = f"{mtu} B" if isinstance(mtu, int) and mtu > 0 else "—"
    state = (port.get("state") or "—").upper()
    state_css = (
        "up" if state == "ACTIVE"
        else "init" if state == "INIT"
        else "down" if state in ("DOWN", "POLLING")
        else ""
    )
    state_html = (
        f"<span class='badge-state {state_css}'>{escape(state)}</span>"
        if state != "—" else "—"
    )
    net = "+".join(dev.get("net_ifaces") or []) or "—"
    driver = dev.get("driver") or "—"
    vendor = dev.get("vendor") or "—"
    fw = dev.get("fw_version") or "—"
    gid = _first_gid(port)
    # v0.5.170 new cells
    model = _resolve_nic_model(vendor)
    pcie = _format_pcie_cell(dev)
    pcie_cls = _format_pcie_badge_class(dev)
    numa = _format_numa_cell(dev)
    ipv4 = _format_ipv4_cell(dev)
    link_html = (
        f"<span class='badge-link'>{escape(link)}</span>"
        if link not in ("—", "Unknown") else escape(link)
    )
    return (
        f"<tr>"
        f"<td class='{side_css}'>{escape(side_disp)}</td>"
        f"<td class='dim'>{escape(str(tg))}</td>"
        f"<td class='code'>{escape(str(hca))}</td>"
        f"<td>{escape(model)}</td>"
        f"<td>{link_html}</td>"
        f"<td class='code'>{escape(rate)}</td>"
        f"<td class='code'>{escape(mtu_txt)}</td>"
        f"<td>{state_html}</td>"
        f"<td class='code {pcie_cls}'>{escape(pcie)}</td>"
        f"<td class='code'>{escape(numa)}</td>"
        f"<td class='code'>{escape(net)}</td>"
        f"<td class='code'>{escape(ipv4)}</td>"
        f"<td class='code'>{escape(driver)}</td>"
        f"<td class='code'>{escape(vendor)}</td>"
        f"<td class='code'>{escape(fw)}</td>"
        f"<td class='code'>{escape(gid)}</td>"
        f"</tr>"
    )


def _first_port(dev: Dict[str, Any]) -> Dict[str, Any]:
    ports = dev.get("ports") or []
    if ports and isinstance(ports[0], dict):
        return ports[0]
    return {}


def _first_gid(port: Dict[str, Any]) -> str:
    gids = port.get("gids") or []
    if not gids:
        return "—"
    # Truncate the long zero-padded form for readability — operator
    # cares about the prefix more than the host portion.
    g = str(gids[0])
    if len(g) > 24:
        return g[:19] + "…"
    return g


def _shorten_rate(rate: Optional[str]) -> str:
    """`/sys` rate is verbose, e.g. "100 Gb/sec (4X EDR)". Strip
    the speed-class suffix — operator cares about the headline
    "100 Gb/sec" in a table cell."""
    if not rate:
        return "—"
    s = str(rate).strip()
    # Drop the trailing "(4X EDR)" classifier if present.
    open_paren = s.find("(")
    if open_paren > 0:
        s = s[:open_paren].strip()
    return s or "—"


# ───── RESULTS TABLE ────────────────────────────────────────────────────


def _render_rows_table(
    rows: List[Dict[str, Any]],
    summary: Optional[Dict[str, Any]],
) -> str:
    if not rows and not summary:
        return "<p class='meta'>—</p>"
    has_lat = any("lat_avg_us" in r and r["lat_avg_us"] is not None
                  for r in rows)
    if has_lat:
        header = (
            "<tr><th>#</th><th>State</th>"
            "<th class='num'>Iters</th>"
            "<th class='num'>Lat avg (µs)</th>"
            "<th class='num'>Lat p99 (µs)</th></tr>"
        )
        body = "".join(_render_lat_row(r) for r in rows)
        if summary:
            body += _render_lat_summary(summary)
    else:
        header = (
            "<tr><th>#</th><th>State</th>"
            "<th class='num'>BW avg (Gbps)</th>"
            "<th class='num'>MsgRate (Mpps)</th>"
            "<th class='num'>Iters</th></tr>"
        )
        body = "".join(_render_bw_row(r) for r in rows)
        if summary:
            body += _render_bw_summary(summary)
    return (
        f"<table class='results'><thead>{header}</thead>"
        f"<tbody>{body}</tbody></table>"
    )


def _render_bw_row(r: Dict[str, Any]) -> str:
    bw = _fmt(r.get("bw_gbps"), 2)
    mr = _fmt(r.get("msgrate_mpps"), 4)
    iters = r.get("iters")
    iters_s = str(iters) if iters is not None else "—"
    return (
        f"<tr><td>{escape(str(r.get('label', '')))}</td>"
        f"<td>{escape(str(r.get('state', '')))}</td>"
        f"<td class='num'>{bw}</td>"
        f"<td class='num'>{mr}</td>"
        f"<td class='num'>{escape(iters_s)}</td></tr>"
    )


def _render_lat_row(r: Dict[str, Any]) -> str:
    avg = _fmt(r.get("lat_avg_us"), 2)
    p99 = _fmt(r.get("lat_p99_us"), 2)
    iters = r.get("iters")
    iters_s = str(iters) if iters is not None else "—"
    return (
        f"<tr><td>{escape(str(r.get('label', '')))}</td>"
        f"<td>{escape(str(r.get('state', '')))}</td>"
        f"<td class='num'>{escape(iters_s)}</td>"
        f"<td class='num'>{avg}</td>"
        f"<td class='num'>{p99}</td></tr>"
    )


def _render_bw_summary(s: Dict[str, Any]) -> str:
    """v0.5.181 polish:
      (#3) Collapse `avg X (min X, max X)` to `avg X` when spread
           is zero — repeating the same value three times was just
           noise (every single-sample run rendered that way).
      (#4) MsgRate column now mirrors the BW column's avg/min/max
           format when min + max are present.
      (#5) Iters column shows the SUM across samples instead of `—`
           (total work done is a useful diagnostic for a run that
           varied per-iteration).

    v0.5.181 followup:
      • `aggregation_mode` (`sum_workers` / `sum_pairs` /
        `avg_iterations`) drives the cell prefix: "total" for
        SUM, "avg" for AVG. Operator's "10.28 → 113" confusion
        on srv06 came from labelling a SUM as `avg`.
      • `workers_attempted` surfaces "N of M reported" when fewer
        workers reported data than were spawned — the partial-
        success case where some workers never completed.
    """
    avg = _fmt(s.get("bw_avg_gbps"), 2)
    mn = _fmt(s.get("bw_min_gbps"), 2)
    mx = _fmt(s.get("bw_max_gbps"), 2)
    mr_avg = _fmt(s.get("msgrate_avg_mpps"), 4)
    mr_min = _fmt(s.get("msgrate_min_mpps"), 4)
    mr_max = _fmt(s.get("msgrate_max_mpps"), 4)
    iters_sum = s.get("iters_sum")
    iters_txt = (str(int(iters_sum))
                 if isinstance(iters_sum, (int, float))
                 else "—")
    n = s.get("samples") or s.get("n") or len(s.get("rows") or []) or "?"
    # v0.5.181 followup: aggregation-mode-aware prefix.
    mode = s.get("aggregation_mode") or "avg_iterations"
    is_sum = mode in ("sum_workers", "sum_pairs")
    prefix = "total" if is_sum else "avg"
    bw_cell = _fmt_summary_cell(
        avg, mn, mx, unit_after_max="", prefix=prefix)
    mr_cell = _fmt_summary_cell(
        mr_avg, mr_min, mr_max, unit_after_max="", prefix=prefix)
    # Samples column: include attempted count when partial.
    # v0.5.181 G-4: sum_pairs mode (Topology) uses pairs_attempted.
    if mode == "sum_pairs":
        attempted = s.get("pairs_attempted")
        unit = "pairs"
    else:
        attempted = s.get("workers_attempted")
        unit = "workers"
    if (isinstance(attempted, int) and attempted
            and isinstance(n, int) and n < attempted):
        samples_txt = f"{n} of {attempted} {unit}"
    else:
        samples_txt = f"{escape(str(n))} samples"
    return (
        f"<tr class='summary'><td>Σ</td>"
        f"<td>{samples_txt}</td>"
        f"<td class='num'>{bw_cell}</td>"
        f"<td class='num'>{mr_cell}</td>"
        f"<td class='num'>{escape(iters_txt)}</td></tr>"
    )


def _fmt_summary_cell(
    avg: str, mn: str, mx: str,
    *, unit_after_max: str = "",
    prefix: str = "avg",
) -> str:
    """v0.5.181 #3: render a Σ-row cell. Drops the `(min X, max X)`
    parens when the spread is zero OR when min/max are unavailable
    (the `—` case). Three distinct outputs:
      • spread zero / no min-max → `<prefix> X`
      • spread present          → `<prefix> X (min Y, max Z)`
      • no avg either           → `—`

    v0.5.181 followup: `prefix` is "avg" for iteration-averaging
    or "total" for worker-sum (parallel-worker BW aggregation).
    """
    if avg == "—":
        return "—"
    if mn == "—" or mx == "—" or mn == avg == mx:
        return f"{prefix} {avg}{unit_after_max}"
    return (f"{prefix} {avg} "
            f"(min {mn}, max {mx}){unit_after_max}")


def _render_lat_summary(s: Dict[str, Any]) -> str:
    """v0.5.181 polish: parity with BW Σ — collapse same-value
    parens, include Iters sum.

    v0.5.182 NB-3 + NB-7: dispatch on aggregation_mode + show
    workers_attempted partial honesty (multi-worker lat tests now
    capture every worker's lat; the samples count should reflect
    the actual reporting workers, not the misleading "1 samples"
    operator saw on srv06). Min/max also rendered when present so
    operator can read jitter without scrolling the per-row table."""
    avg = _fmt(s.get("lat_avg_us"), 2)
    mn = _fmt(s.get("lat_min_us"), 2)
    mx = _fmt(s.get("lat_max_us"), 2)
    p99 = _fmt(s.get("lat_p99_us"), 2)
    iters_sum = s.get("iters_sum")
    iters_txt = (str(int(iters_sum))
                 if isinstance(iters_sum, (int, float))
                 else "—")
    n = s.get("samples") or s.get("n") or "?"
    avg_cell = _fmt_summary_cell(avg, mn, mx, unit_after_max="")
    # v0.5.182 NB-3: pick the workers_attempted / pairs_attempted
    # surface based on the aggregation mode. Lat tests across N
    # parallel workers should show "X of Y workers" honesty so a
    # partial-reporting run isn't masked as "1 sample".
    mode = s.get("aggregation_mode") or ""
    if mode == "sum_pairs":
        attempted = s.get("pairs_attempted")
        unit = "pairs"
    else:
        attempted = s.get("workers_attempted")
        unit = "workers"
    if (isinstance(attempted, int) and attempted
            and isinstance(n, int) and n < attempted):
        samples_txt = f"{n} of {attempted} {unit}"
    elif (isinstance(attempted, int) and attempted
          and isinstance(n, int)):
        samples_txt = f"{n} {unit}"
    else:
        samples_txt = f"{escape(str(n))} samples"
    return (
        f"<tr class='summary'><td>Σ</td>"
        f"<td>{samples_txt}</td>"
        f"<td class='num'>{escape(iters_txt)}</td>"
        f"<td class='num'>{avg_cell}</td>"
        f"<td class='num'>{p99}</td></tr>"
    )


def _fmt(v: Any, places: int) -> str:
    if isinstance(v, (int, float)):
        return f"{float(v):.{places}f}"
    return "—"


# ───── v0.5.177 RFC 2544-style latency-vs-size sweep ─────────────


def _fmt_bytes(n: int) -> str:
    """Human-readable message size: 2 B, 64 B, 1 KiB, 1 MiB."""
    if n < 1024:
        return f"{n} B"
    if n < 1024 * 1024:
        return f"{n // 1024} KiB"
    return f"{n // (1024 * 1024)} MiB"


def _render_lat_sweep_section(
    sweep: List[Dict[str, Any]],
    params: Dict[str, Any],
) -> str:
    """RFC 2544-style latency-vs-size table + inline SVG line chart.

    Operators reading this section want one thing fast: the
    latency curve as a function of message size. We render the
    table first (sortable in any browser by copy-paste) and put
    the chart above it as a visual orientation. The chart is
    inline SVG so the report file stays self-contained — no JS,
    no external assets.

    Empty sweep → empty string (no section header). Single-row
    sweeps still render but the chart degrades to one point — the
    table is the carrier in that case.
    """
    if not sweep:
        return ""
    # Sort by message size so the chart x-axis is monotonic even if
    # perftest emitted rows out of order on a recovery / retry path.
    rows = sorted(sweep, key=lambda r: int(r.get("bytes") or 0))
    per_size = params.get("iterations_per_size")
    per_size_txt = (
        f" · {per_size} iters/size" if per_size else "")
    header = (
        "<h3 style='margin-top:18px;'>"
        "Latency vs Message Size "
        "<span style='font-size:12px; color:#6b7280; font-weight:400;'>"
        f"(RFC 2544-style{per_size_txt})</span>"
        "</h3>"
    )
    chart = _render_lat_sweep_chart(rows)
    table = _render_lat_sweep_table(rows)
    return f"{header}{chart}{table}"


def _render_lat_sweep_chart(rows: List[Dict[str, Any]]) -> str:
    """Inline SVG: log-x message size, linear-y µs. One line for
    avg latency, lighter band for min↔max envelope. No JS — pure
    SVG so the report stays self-contained when archived."""
    sizes = [int(r["bytes"]) for r in rows if r.get("bytes")]
    avgs = [r.get("lat_avg_us") for r in rows]
    mins = [r.get("lat_min_us") for r in rows]
    maxs = [r.get("lat_max_us") for r in rows]
    p99s = [r.get("lat_p99_us") for r in rows]
    if not sizes or not any(isinstance(a, (int, float)) for a in avgs):
        return ""
    import math as _m
    # Plot box.
    W, H = 700, 280
    PAD_L, PAD_R, PAD_T, PAD_B = 56, 20, 18, 40
    plot_w = W - PAD_L - PAD_R
    plot_h = H - PAD_T - PAD_B
    # Log-x — perftest sizes are powers of two so log2 spans evenly.
    log_min = _m.log2(min(sizes))
    log_max = _m.log2(max(sizes))
    log_span = max(log_max - log_min, 1.0)
    # Linear-y, padded 5%.
    valid_lats: List[float] = []
    for vals in (mins, avgs, maxs, p99s):
        valid_lats.extend(
            v for v in vals if isinstance(v, (int, float)))
    y_min = 0.0
    y_max = max(valid_lats) * 1.10 if valid_lats else 1.0

    def x_of(b: int) -> float:
        return PAD_L + ((_m.log2(b) - log_min) / log_span) * plot_w

    def y_of(v: float) -> float:
        return PAD_T + plot_h - ((v - y_min) / (y_max - y_min)) * plot_h
    # Y axis gridlines at 5 evenly-spaced µs values.
    grid_lines = []
    for i in range(5):
        v = y_min + (i / 4.0) * (y_max - y_min)
        y = y_of(v)
        grid_lines.append(
            f"<line x1='{PAD_L}' y1='{y:.1f}' x2='{W - PAD_R}' "
            f"y2='{y:.1f}' stroke='#e5e7eb' stroke-width='1'/>"
            f"<text x='{PAD_L - 6}' y='{y + 4:.1f}' "
            f"text-anchor='end' font-size='10' fill='#6b7280'>"
            f"{v:.1f}</text>"
        )
    # X axis size labels — every other power-of-two so the labels
    # don't overlap on dense sweeps.
    x_labels = []
    for i, b in enumerate(sizes):
        if i % 2 == 0 or i == len(sizes) - 1:
            x = x_of(b)
            x_labels.append(
                f"<text x='{x:.1f}' y='{H - PAD_B + 14}' "
                f"text-anchor='middle' font-size='10' fill='#6b7280'>"
                f"{_fmt_bytes(b)}</text>"
            )
    # Min/max envelope.
    envelope_parts: List[str] = []
    have_envelope = (
        any(isinstance(v, (int, float)) for v in mins)
        and any(isinstance(v, (int, float)) for v in maxs))
    if have_envelope:
        # Forward (min) then reverse (max) → closed polygon.
        fwd = " ".join(
            f"{x_of(b):.1f},{y_of(float(v)):.1f}"
            for b, v in zip(sizes, mins)
            if isinstance(v, (int, float)))
        rev = " ".join(
            f"{x_of(b):.1f},{y_of(float(v)):.1f}"
            for b, v in reversed(list(zip(sizes, maxs)))
            if isinstance(v, (int, float)))
        envelope_parts.append(
            f"<polygon points='{fwd} {rev}' fill='#a7f3d0' "
            f"fill-opacity='0.45' stroke='none'/>"
        )
    # Avg line.
    avg_pts = [
        f"{x_of(b):.1f},{y_of(float(v)):.1f}"
        for b, v in zip(sizes, avgs)
        if isinstance(v, (int, float))
    ]
    avg_line = (
        f"<polyline fill='none' stroke='#059669' stroke-width='2' "
        f"points='{' '.join(avg_pts)}'/>" if avg_pts else "")
    # Avg circles.
    avg_dots = "".join(
        f"<circle cx='{x_of(b):.1f}' cy='{y_of(float(v)):.1f}' "
        f"r='3' fill='#065f46'/>"
        for b, v in zip(sizes, avgs)
        if isinstance(v, (int, float))
    )
    # p99 line (dashed) if available.
    p99_pts = [
        f"{x_of(b):.1f},{y_of(float(v)):.1f}"
        for b, v in zip(sizes, p99s)
        if isinstance(v, (int, float))
    ]
    p99_line = (
        f"<polyline fill='none' stroke='#b45309' stroke-width='1.5' "
        f"stroke-dasharray='4,3' points='{' '.join(p99_pts)}'/>"
        if p99_pts else "")
    # Legend.
    legend = (
        f"<g transform='translate({PAD_L + 8},{PAD_T + 4})' "
        f"font-size='10' fill='#374151'>"
        f"<line x1='0' y1='4' x2='14' y2='4' stroke='#059669' "
        f"stroke-width='2'/>"
        f"<text x='18' y='8'>avg</text>"
    )
    legend_x = 46
    if p99_pts:
        legend += (
            f"<line x1='{legend_x}' y1='4' x2='{legend_x + 14}' "
            f"y2='4' stroke='#b45309' stroke-width='1.5' "
            f"stroke-dasharray='4,3'/>"
            f"<text x='{legend_x + 18}' y='8'>p99</text>"
        )
        legend_x += 50
    if have_envelope:
        legend += (
            f"<rect x='{legend_x}' y='0' width='14' height='8' "
            f"fill='#a7f3d0' fill-opacity='0.55'/>"
            f"<text x='{legend_x + 18}' y='8'>min–max</text>"
        )
    legend += "</g>"
    # Y axis label.
    y_label = (
        f"<text x='{PAD_L - 38}' y='{PAD_T + plot_h / 2}' "
        f"transform='rotate(-90 {PAD_L - 38} {PAD_T + plot_h / 2})' "
        f"text-anchor='middle' font-size='11' fill='#374151' "
        f"font-weight='600'>Latency (µs)</text>"
    )
    return (
        f"<div style='margin:8px 0 14px 0; "
        f"border:1px solid #e5e7eb; border-radius:6px; "
        f"padding:6px 4px;'>"
        f"<svg viewBox='0 0 {W} {H}' width='100%' "
        f"style='max-width:{W}px; display:block;'>"
        f"{''.join(grid_lines)}"
        f"{''.join(envelope_parts)}"
        f"{avg_line}{p99_line}{avg_dots}"
        f"{''.join(x_labels)}"
        f"{y_label}{legend}"
        f"</svg></div>"
    )


def _render_lat_sweep_table(rows: List[Dict[str, Any]]) -> str:
    header = (
        "<tr>"
        "<th>Size</th>"
        "<th class='num'>Iters</th>"
        "<th class='num'>Min (µs)</th>"
        "<th class='num'>Typ (µs)</th>"
        "<th class='num'>Avg (µs)</th>"
        "<th class='num'>Max (µs)</th>"
        "<th class='num'>StdDev (µs)</th>"
        "<th class='num'>p99 (µs)</th>"
        "<th class='num'>p99.9 (µs)</th>"
        "</tr>"
    )
    body = "".join(
        "<tr>"
        f"<td>{_fmt_bytes(int(r.get('bytes') or 0))}</td>"
        f"<td class='num'>{r.get('iters', '—')}</td>"
        f"<td class='num'>{_fmt(r.get('lat_min_us'), 2)}</td>"
        f"<td class='num'>{_fmt(r.get('lat_typ_us'), 2)}</td>"
        f"<td class='num'>{_fmt(r.get('lat_avg_us'), 2)}</td>"
        f"<td class='num'>{_fmt(r.get('lat_max_us'), 2)}</td>"
        f"<td class='num'>{_fmt(r.get('lat_stdev_us'), 2)}</td>"
        f"<td class='num'>{_fmt(r.get('lat_p99_us'), 2)}</td>"
        f"<td class='num'>{_fmt(r.get('lat_p999_us'), 2)}</td>"
        "</tr>"
        for r in rows
    )
    return (
        f"<table class='results'>"
        f"<thead>{header}</thead>"
        f"<tbody>{body}</tbody></table>"
    )
