"""v0.5.163: shared HTML-report builder for the Blast + Topology
RDMA dialogs.

Operator: "also allow user to generate report for this test both
in via blast test and topology test" — HTML format, scope = all
runs since the dialog opened (append-only session log).

v0.5.167 redesign: operator flagged the prior report as low-info
and hard to scan. Three fixes:

1. **Endpoint details** — each run now carries a per-side device
   dump (NIC vendor / model / driver / link rate / MTU / FW /
   GIDs / netdevs), rendered as a small table.
2. **Key result callout** — the BW headline is pulled to the
   top of each run-card so the operator doesn't have to scroll
   to the Results table.
3. **Visibility pass** — paired param table (the old grid was
   spreading dt/dd as independent cells, so labels and values
   interleaved); zebra-stripe tables; left-stripe on the run
   card; clearer hierarchy.

Each dialog maintains a `_run_log: List[Dict]` instance var.
Every completed run (single iteration or one bulk iterate-N
session) appends a dict with the metadata + per-row results.
The Export button passes that list here.

Schema for one run entry:

  {
    "kind":          "blast" | "topology",
    "started_at":    ISO string (operator-provided wall-clock),
    "test":          "ib_send_bw" | ... ,
    "params":        {msg_size, qp_count, mtu, tx_depth, gid_index,
                      bidirectional, cpu_util, parallel_workers,
                      iterations, shape (topology only)},
    "endpoints":     {server: "<host> <hca>", client: "..."} or
                     {pairs: [{idx, server, client}, ...]}
    "endpoint_details":  # v0.5.167 — optional
                     [{side, tg, hca, device: {...payload from
                       /api/rdma/devices...}, pair_index?}, ...]
    "rows":          [{label, bw_gbps, msgrate_mpps, lat_avg_us,
                       state}, ...]
    "summary":       {bw_avg, bw_min, bw_max, msgrate_avg, ...} |
                     None
  }

The HTML is self-contained (inline CSS), no external assets.
Operators can email / archive the file as-is.
"""
from __future__ import annotations

import re
from html import escape
from typing import Any, Dict, List, Optional


# v0.5.167: human-readable param labels. Falls through to the raw
# key when not in the map — so brand-new params show up without
# code changes here, just less polished.
_PARAM_LABELS: Dict[str, str] = {
    "test": "Test",
    "msg_size": "Message size",
    "qp_count": "QP count",
    "duration_s": "Duration",
    "tx_depth": "TX depth",
    "gid_index": "GID index",
    "mtu": "MTU",
    "bidirectional": "Bidirectional",
    "cpu_util": "CPU util reporting",
    "parallel_workers": "Parallel workers",
    "iterations": "Iterations",
    "shape": "Topology shape",
    "base_port": "Base port",
}


_PARAM_UNITS: Dict[str, str] = {
    "msg_size": "B",
    "duration_s": "s",
}


def build_html_report(
    *,
    title: str,
    runs: List[Dict[str, Any]],
    generated_at: str,
    client_version: Optional[str] = None,
) -> str:
    """Render the full HTML document. `runs` is the append-only
    session log (oldest first). `generated_at` is the operator-
    side wall-clock at export time (the dialog passes this in so
    the function stays pure / testable)."""
    head = _render_head(title)
    intro = _render_intro(title, generated_at, len(runs), client_version)
    body = "".join(_render_run_section(i, r) for i, r in enumerate(runs))
    if not runs:
        body = (
            "<p class='empty'>No runs recorded yet. Run a test and "
            "click Export Report again.</p>"
        )
    footer = (
        "<footer>Generated by netgen RDMA dialogs. "
        "Self-contained HTML — safe to archive or email.</footer>"
    )
    return (
        f"<!DOCTYPE html>\n<html lang='en'><head>{head}</head>"
        f"<body><main class='container'>{intro}{body}{footer}</main>"
        f"</body></html>"
    )


# ───── HEAD / INTRO ────────────────────────────────────────────────────


def _render_head(title: str) -> str:
    css = """
        :root {
          --fg: #0f172a; --muted: #475569; --line: #cbd5e1;
          --card: #f8fafc; --accent: #1d4ed8;
          --warn: #b45309; --ok: #047857; --err: #b91c1c;
          --stripe: #f1f5f9; --headline: #064e3b; --headline-bg: #ecfdf5;
          --pill-bg: #e0e7ff; --kv-label: #475569;
        }
        * { box-sizing: border-box; }
        body {
          font-family: -apple-system, BlinkMacSystemFont, "Segoe UI",
                       Roboto, sans-serif;
          color: var(--fg); background: #fff; margin: 0;
          line-height: 1.5;
        }
        .container { max-width: 1180px; margin: 0 auto; padding: 24px; }
        h1 { font-size: 22px; margin: 0 0 4px; }
        h2 {
          font-size: 17px; margin: 0 0 4px;
        }
        h3 {
          font-size: 12px; margin: 18px 0 6px; color: var(--muted);
          text-transform: uppercase; letter-spacing: 0.5px;
          font-weight: 700;
        }
        .meta { color: var(--muted); font-size: 12px; margin-bottom: 16px; }
        .meta strong { color: var(--fg); font-weight: 600; }
        .empty {
          padding: 16px; background: var(--card); border-radius: 6px;
          color: var(--muted); font-style: italic;
        }
        /* Run card with left accent stripe — operators scanning
           a multi-run report need a clear visual divider per run. */
        .run-card {
          background: var(--card);
          border: 1px solid var(--line); border-left: 4px solid var(--accent);
          border-radius: 6px; padding: 16px 18px; margin-bottom: 18px;
        }
        .run-head {
          display: flex; align-items: baseline; gap: 10px;
          flex-wrap: wrap;
        }
        .run-head .timestamp {
          color: var(--muted); font-size: 12px;
        }
        /* The big-number headline — operators read this first and
           often stop here. Mirrors the in-app post-run card. */
        .headline {
          margin-top: 10px; padding: 8px 12px;
          background: var(--headline-bg);
          border: 1px solid #10b981; border-radius: 4px;
          color: var(--headline);
        }
        .headline .num { font-size: 22px; font-weight: 700; }
        .headline .num.mr { font-size: 16px; }
        .headline .unit { font-size: 11px; color: #065f46; }
        .headline .tail { font-size: 11px; color: #047857; margin-left: 4px; }
        .headline .sep { color: #475569; padding: 0 4px; }
        /* Param table — two columns of {label, value} pairs.
           Earlier versions used a `display: grid` over <dt>/<dd>
           which spread labels and values into independent cells,
           interleaving them. The <table> + paired rows fix is
           verbose-source but bullet-proof. */
        table.params, table.endpoints, table.results {
          width: 100%; border-collapse: collapse; font-size: 12px;
          margin-top: 6px;
        }
        table.params td {
          padding: 4px 10px;
          border-bottom: 1px solid var(--line);
          vertical-align: top;
        }
        table.params td.k {
          color: var(--kv-label); font-weight: 500; width: 28%;
        }
        table.params td.v {
          font-family: "SF Mono", Menlo, Consolas, monospace;
        }
        table.endpoints th, table.endpoints td,
        table.results th, table.results td {
          padding: 6px 10px; text-align: left;
          border-bottom: 1px solid var(--line);
        }
        table.endpoints th, table.results th {
          color: var(--muted); font-weight: 600;
          background: #eef2f7; font-size: 11px;
          text-transform: uppercase; letter-spacing: 0.3px;
        }
        table.endpoints tbody tr:nth-child(even),
        table.results tbody tr:nth-child(even) {
          background: var(--stripe);
        }
        table.endpoints td.code, table.endpoints td.dim {
          font-family: "SF Mono", Menlo, Consolas, monospace;
          font-size: 11px;
        }
        table.endpoints td.dim { color: var(--muted); }
        table.endpoints td.side-srv { color: var(--accent); font-weight: 600; }
        table.endpoints td.side-cli { color: var(--ok); font-weight: 600; }
        td.num {
          font-family: "SF Mono", Menlo, Consolas, monospace;
          text-align: right;
        }
        tr.summary { background: #eef2ff !important; font-weight: 600; }
        tr.summary td { border-top: 2px solid var(--accent); }
        .pill {
          display: inline-block; padding: 1px 8px; border-radius: 10px;
          font-size: 11px; background: var(--pill-bg); color: var(--accent);
          text-transform: lowercase;
        }
        .badge-link, .badge-state {
          display: inline-block; padding: 1px 6px; border-radius: 3px;
          font-size: 10px; font-weight: 600; letter-spacing: 0.3px;
        }
        .badge-link {
          background: #dbeafe; color: var(--accent);
          text-transform: uppercase;
        }
        .badge-state.up { background: #d1fae5; color: var(--ok); }
        .badge-state.down { background: #fee2e2; color: var(--err); }
        .badge-state.init { background: #fef3c7; color: var(--warn); }
        /* v0.5.170: PCIe downgrade warning — operator-critical
           signal. Yellow background draws the eye without
           screaming red (the link is working, just not at full
           capability). */
        .pcie-warn {
          background: #fef3c7;
          color: var(--warn);
          font-weight: 600;
        }
        footer { color: var(--muted); font-size: 11px; margin-top: 32px;
          padding-top: 12px; border-top: 1px solid var(--line);
        }
    """
    return (
        f"<meta charset='utf-8'>"
        f"<title>{escape(title)}</title>"
        f"<style>{css}</style>"
    )


def _render_intro(
    title: str, generated_at: str, n_runs: int,
    client_version: Optional[str],
) -> str:
    ver = (
        f" &middot; netgen {escape(client_version)}"
        if client_version else ""
    )
    return (
        f"<h1>{escape(title)}</h1>"
        f"<div class='meta'>"
        f"<strong>Generated:</strong> {escape(generated_at)}{ver}"
        f" &middot; <strong>{n_runs} run"
        f"{'s' if n_runs != 1 else ''}</strong>"
        f"</div>"
    )


# ───── PER-RUN SECTION ─────────────────────────────────────────────────


def _render_run_section(idx: int, run: Dict[str, Any]) -> str:
    head = (
        f"<div class='run-head'>"
        f"<h2>Run #{idx + 1}"
        f" &middot; <span class='pill'>{escape(run.get('kind') or '?')}</span>"
        f" &middot; {escape(run.get('test') or '?')}</h2>"
        f"<span class='timestamp'>started at "
        f"{escape(run.get('started_at') or '?')}</span>"
        f"</div>"
    )
    headline = _render_headline(run)
    params = _render_params(run.get("params") or {})
    endpoints = _render_endpoints(
        run.get("endpoints") or {},
        run.get("endpoint_details") or [],
    )
    rows = _render_rows_table(
        run.get("rows") or [],
        run.get("summary") or None,
    )
    return (
        f"<section class='run-card'>"
        f"{head}{headline}"
        f"<h3>Parameters</h3>{params}"
        f"<h3>Endpoints</h3>{endpoints}"
        f"<h3>Results</h3>{rows}"
        f"</section>"
    )


_RATE_RE = re.compile(r"([0-9]+(?:\.[0-9]+)?)\s*Gb/sec",
                       re.IGNORECASE)


def _extract_line_rate_gbps(run: Dict[str, Any]) -> Optional[float]:
    """v0.5.170: pull a line-rate number from the endpoint details
    so we can show `BW / line-rate %` in the headline. Uses the
    SLOWEST endpoint as the cap — a 200 G ↔ 100 G run is capped
    at 100 G end-to-end. Returns None when we can't parse any
    endpoint's rate (legacy run_log entries without details)."""
    details = run.get("endpoint_details") or []
    rates: List[float] = []
    for d in details:
        dev = d.get("device") or {}
        ports = dev.get("ports") or []
        for p in ports:
            r = (p.get("rate") or "")
            m = _RATE_RE.search(r)
            if m:
                try:
                    rates.append(float(m.group(1)))
                    break
                except ValueError:
                    pass
    return min(rates) if rates else None


def _render_headline(run: Dict[str, Any]) -> str:
    """v0.5.167: key-result callout at the top of the run card.
    Pulls the headline BW + MsgRate from `summary` (or the lone
    `rows` entry for one-shot runs). Mirrors the dialog's post-run
    card so the export carries the same first-glance number.

    v0.5.170: appends `· X% of N G` line-rate efficiency when the
    endpoint table can supply a rate. Lets operators tell at a
    glance whether the test hit line rate (>90% = good).
    """
    summary = run.get("summary") or {}
    rows = run.get("rows") or []
    if (isinstance(summary.get("bw_avg_gbps"), (int, float))
            and summary.get("samples", 0) > 1):
        bw = float(summary["bw_avg_gbps"])
        tail = f"average across {int(summary['samples'])} samples"
    else:
        bws = [r["bw_gbps"] for r in rows
               if isinstance(r.get("bw_gbps"), (int, float))]
        bw = max(bws) if bws else None
        tail = "final"
    if isinstance(summary.get("msgrate_avg_mpps"), (int, float)):
        mr: Optional[float] = float(summary["msgrate_avg_mpps"])
    else:
        mrs = [r["msgrate_mpps"] for r in rows
               if isinstance(r.get("msgrate_mpps"), (int, float))]
        mr = mrs[-1] if mrs else None
    if bw is None and mr is None:
        return ""
    bw_txt = f"{bw:.2f}" if isinstance(bw, float) else "—"
    mr_txt = f"{mr:.4f}" if isinstance(mr, float) else "—"
    extras = []
    if isinstance(summary.get("bw_min_gbps"), (int, float)) \
            and isinstance(summary.get("bw_max_gbps"), (int, float)) \
            and summary.get("samples", 0) > 1:
        extras.append(
            f"min {summary['bw_min_gbps']:.2f} / "
            f"max {summary['bw_max_gbps']:.2f} Gbps"
        )
    # v0.5.170: line-rate efficiency. Operators ask this every
    # run: "did we hit line rate?" Show the % up front.
    line_rate = _extract_line_rate_gbps(run)
    if isinstance(bw, float) and line_rate and line_rate > 0:
        pct = (bw / line_rate) * 100.0
        extras.append(
            f"{pct:.1f}% of {line_rate:g} G line rate")
    tail_html = escape(tail)
    if extras:
        tail_html += " &middot; " + " &middot; ".join(escape(b) for b in extras)
    return (
        f"<div class='headline'>"
        f"<span class='num'>{bw_txt}</span>"
        f"<span class='unit'> Gbps</span>"
        f"<span class='sep'>|</span>"
        f"<span class='num mr'>{mr_txt}</span>"
        f"<span class='unit'> Mpps</span>"
        f"<span class='tail'>&middot; {tail_html}</span>"
        f"</div>"
    )


def _render_params(params: Dict[str, Any]) -> str:
    """v0.5.167: paired-row table instead of dl/dt/dd grid.

    The old `display: grid; grid-template-columns: auto-fill` over
    dt/dd treated each <dt> and <dd> as an independent cell, so
    labels and values interleaved when the column count didn't
    line up. A <table> with one row per pair eliminates the bug
    and keeps the report readable on narrow viewports."""
    if not params:
        return "<p class='meta'>—</p>"
    rows = []
    for k, v in params.items():
        label = _PARAM_LABELS.get(str(k), str(k))
        v_str = _format_param_value(k, v)
        rows.append(
            f"<tr><td class='k'>{escape(label)}</td>"
            f"<td class='v'>{escape(v_str)}</td></tr>"
        )
    return f"<table class='params'><tbody>{''.join(rows)}</tbody></table>"


def _format_param_value(key: str, value: Any) -> str:
    if isinstance(value, bool):
        return "yes" if value else "no"
    unit = _PARAM_UNITS.get(str(key), "")
    return f"{value}{(' ' + unit) if unit else ''}"


# ───── ENDPOINTS ───────────────────────────────────────────────────────


_ENDPOINT_HEADERS = (
    "Side", "TG", "HCA", "Model", "Link", "Rate", "MTU", "State",
    "PCIe", "NUMA", "NetDev", "IPv4", "Driver", "Vendor", "FW",
    "GID",
)


# v0.5.170: Mellanox board_id → friendly product name. Operators
# read "ConnectX-7" not "MT_0000000838". Mirrors the mapping the
# admin console uses (v0.5.73). Falls through to the raw board_id
# when unknown — adding a missing prefix later is a one-line
# diff. The mapping is *prefix*-based; revisions append digits
# but the first 4-6 hex digits identify the product family.
_BOARD_ID_TO_MODEL = {
    "MT_0000000200": "ConnectX-3 Pro",
    "MT_0000000418": "ConnectX-5",
    "MT_0000000414": "ConnectX-5",
    "MT_0000000437": "ConnectX-6",
    "MT_0000000591": "ConnectX-6 Dx",
    "MT_0000000610": "ConnectX-6 Lx",
    "MT_0000000838": "ConnectX-7",
    "MT_0000000883": "ConnectX-7",
    "MT_0000001019": "ConnectX-8",
    # Broadcom (Thor / Thor2)
    "BCM5755X": "BCM Thor",
    "BCM5760X": "BCM Thor2",
    # AMD Pollara
    "ATI0001":   "Pollara 400",
}


def _resolve_nic_model(vendor: Optional[str]) -> str:
    """Return a friendly product name for the HCA, or `—` when we
    don't recognise the board_id. The mapping is prefix-based so
    future revisions of an existing product still match."""
    if not vendor:
        return "—"
    v = str(vendor).strip().upper()
    # Exact match first.
    if v in _BOARD_ID_TO_MODEL:
        return _BOARD_ID_TO_MODEL[v]
    # Prefix match — board_ids sometimes append a revision suffix.
    for key, model in _BOARD_ID_TO_MODEL.items():
        if v.startswith(key):
            return model
    return "—"


def _format_pcie_cell(dev: Dict[str, Any]) -> str:
    """`Gen4 x16` or `Gen4 x16 (max Gen5 x16)` when downgraded.
    `—` when the HCA didn't report PCIe info."""
    gen = dev.get("pcie_gen")
    width = dev.get("pcie_current_width")
    if not gen and not width:
        return "—"
    cur = f"Gen{gen}" if gen else "Gen?"
    if width:
        cur += f" x{width}"
    if dev.get("pcie_downgraded"):
        max_gen = dev.get("pcie_max_gen")
        max_w = dev.get("pcie_max_width")
        cap_bits = []
        if max_gen:
            cap_bits.append(f"Gen{max_gen}")
        if max_w:
            cap_bits.append(f"x{max_w}")
        if cap_bits:
            cur += f" (max {' '.join(cap_bits)})"
    return cur


def _format_pcie_badge_class(dev: Dict[str, Any]) -> str:
    """CSS class for the PCIe cell — `pcie-warn` when downgraded
    so the operator's eye snaps to it."""
    return "pcie-warn" if dev.get("pcie_downgraded") else ""


def _format_ipv4_cell(dev: Dict[str, Any]) -> str:
    """Pick the first IPv4 across the HCA's netdevs. Most HCAs
    expose one netdev; bonded HCAs expose multiple — we show
    only the first to keep the column narrow. The remaining IPs
    are still in the JSON payload for power users."""
    ips_by_iface = dev.get("netdev_ips") or {}
    for iface, ip_list in ips_by_iface.items():
        for ip in ip_list:
            if "." in ip.split("/", 1)[0]:
                return ip
    return "—"


def _format_numa_cell(dev: Dict[str, Any]) -> str:
    n = dev.get("numa_node")
    return f"node {n}" if isinstance(n, int) else "—"


def _render_endpoints(
    eps: Dict[str, Any],
    details: List[Dict[str, Any]],
) -> str:
    """v0.5.167: rich endpoint table when `endpoint_details` is
    present. Falls back to the legacy server/client string block
    or pairs list for back-compat (old run_log entries without
    rich data shouldn't crash the renderer)."""
    if details:
        return _render_endpoint_table(details)
    if "pairs" in eps:
        items = "".join(
            f"<li>#{escape(str(p.get('idx', '?')))} "
            f"<code>{escape(str(p.get('server', '?')))}</code> "
            f"&rarr; <code>{escape(str(p.get('client', '?')))}</code>"
            f"</li>"
            for p in eps.get("pairs") or []
        )
        return f"<ul>{items}</ul>" if items else "<p class='meta'>—</p>"
    server = eps.get("server")
    client = eps.get("client")
    if server or client:
        return (
            f"<p><strong>Server:</strong> "
            f"<code>{escape(str(server or '?'))}</code><br>"
            f"<strong>Client:</strong> "
            f"<code>{escape(str(client or '?'))}</code></p>"
        )
    return "<p class='meta'>—</p>"


def _render_endpoint_table(details: List[Dict[str, Any]]) -> str:
    if not details:
        return "<p class='meta'>—</p>"
    header = "".join(f"<th>{h}</th>" for h in _ENDPOINT_HEADERS)
    body = "".join(_render_endpoint_row(d) for d in details)
    return (
        f"<table class='endpoints'><thead><tr>{header}</tr></thead>"
        f"<tbody>{body}</tbody></table>"
    )


def _render_endpoint_row(d: Dict[str, Any]) -> str:
    side = (d.get("side") or "?").lower()
    side_css = f"side-{'srv' if side.startswith('s') else 'cli'}"
    side_disp = "server" if side.startswith("s") else "client"
    if d.get("pair_index") is not None:
        side_disp = f"#{d['pair_index']} {side_disp}"
    tg = d.get("tg") or ""
    hca = d.get("hca") or "?"
    dev = d.get("device") or {}
    port = _first_port(dev)
    link = port.get("link_layer") or "—"
    rate = _shorten_rate(port.get("rate"))
    mtu = port.get("mtu")
    mtu_txt = f"{mtu} B" if isinstance(mtu, int) and mtu > 0 else "—"
    state = (port.get("state") or "—").upper()
    state_css = (
        "up" if state == "ACTIVE"
        else "init" if state == "INIT"
        else "down" if state in ("DOWN", "POLLING")
        else ""
    )
    state_html = (
        f"<span class='badge-state {state_css}'>{escape(state)}</span>"
        if state != "—" else "—"
    )
    net = "+".join(dev.get("net_ifaces") or []) or "—"
    driver = dev.get("driver") or "—"
    vendor = dev.get("vendor") or "—"
    fw = dev.get("fw_version") or "—"
    gid = _first_gid(port)
    # v0.5.170 new cells
    model = _resolve_nic_model(vendor)
    pcie = _format_pcie_cell(dev)
    pcie_cls = _format_pcie_badge_class(dev)
    numa = _format_numa_cell(dev)
    ipv4 = _format_ipv4_cell(dev)
    link_html = (
        f"<span class='badge-link'>{escape(link)}</span>"
        if link not in ("—", "Unknown") else escape(link)
    )
    return (
        f"<tr>"
        f"<td class='{side_css}'>{escape(side_disp)}</td>"
        f"<td class='dim'>{escape(str(tg))}</td>"
        f"<td class='code'>{escape(str(hca))}</td>"
        f"<td>{escape(model)}</td>"
        f"<td>{link_html}</td>"
        f"<td class='code'>{escape(rate)}</td>"
        f"<td class='code'>{escape(mtu_txt)}</td>"
        f"<td>{state_html}</td>"
        f"<td class='code {pcie_cls}'>{escape(pcie)}</td>"
        f"<td class='code'>{escape(numa)}</td>"
        f"<td class='code'>{escape(net)}</td>"
        f"<td class='code'>{escape(ipv4)}</td>"
        f"<td class='code'>{escape(driver)}</td>"
        f"<td class='code'>{escape(vendor)}</td>"
        f"<td class='code'>{escape(fw)}</td>"
        f"<td class='code'>{escape(gid)}</td>"
        f"</tr>"
    )


def _first_port(dev: Dict[str, Any]) -> Dict[str, Any]:
    ports = dev.get("ports") or []
    if ports and isinstance(ports[0], dict):
        return ports[0]
    return {}


def _first_gid(port: Dict[str, Any]) -> str:
    gids = port.get("gids") or []
    if not gids:
        return "—"
    # Truncate the long zero-padded form for readability — operator
    # cares about the prefix more than the host portion.
    g = str(gids[0])
    if len(g) > 24:
        return g[:19] + "…"
    return g


def _shorten_rate(rate: Optional[str]) -> str:
    """`/sys` rate is verbose, e.g. "100 Gb/sec (4X EDR)". Strip
    the speed-class suffix — operator cares about the headline
    "100 Gb/sec" in a table cell."""
    if not rate:
        return "—"
    s = str(rate).strip()
    # Drop the trailing "(4X EDR)" classifier if present.
    open_paren = s.find("(")
    if open_paren > 0:
        s = s[:open_paren].strip()
    return s or "—"


# ───── RESULTS TABLE ────────────────────────────────────────────────────


def _render_rows_table(
    rows: List[Dict[str, Any]],
    summary: Optional[Dict[str, Any]],
) -> str:
    if not rows and not summary:
        return "<p class='meta'>—</p>"
    has_lat = any("lat_avg_us" in r and r["lat_avg_us"] is not None
                  for r in rows)
    if has_lat:
        header = (
            "<tr><th>#</th><th>State</th>"
            "<th class='num'>Iters</th>"
            "<th class='num'>Lat avg (µs)</th>"
            "<th class='num'>Lat p99 (µs)</th></tr>"
        )
        body = "".join(_render_lat_row(r) for r in rows)
        if summary:
            body += _render_lat_summary(summary)
    else:
        header = (
            "<tr><th>#</th><th>State</th>"
            "<th class='num'>BW avg (Gbps)</th>"
            "<th class='num'>MsgRate (Mpps)</th>"
            "<th class='num'>Iters</th></tr>"
        )
        body = "".join(_render_bw_row(r) for r in rows)
        if summary:
            body += _render_bw_summary(summary)
    return (
        f"<table class='results'><thead>{header}</thead>"
        f"<tbody>{body}</tbody></table>"
    )


def _render_bw_row(r: Dict[str, Any]) -> str:
    bw = _fmt(r.get("bw_gbps"), 2)
    mr = _fmt(r.get("msgrate_mpps"), 4)
    iters = r.get("iters")
    iters_s = str(iters) if iters is not None else "—"
    return (
        f"<tr><td>{escape(str(r.get('label', '')))}</td>"
        f"<td>{escape(str(r.get('state', '')))}</td>"
        f"<td class='num'>{bw}</td>"
        f"<td class='num'>{mr}</td>"
        f"<td class='num'>{escape(iters_s)}</td></tr>"
    )


def _render_lat_row(r: Dict[str, Any]) -> str:
    avg = _fmt(r.get("lat_avg_us"), 2)
    p99 = _fmt(r.get("lat_p99_us"), 2)
    iters = r.get("iters")
    iters_s = str(iters) if iters is not None else "—"
    return (
        f"<tr><td>{escape(str(r.get('label', '')))}</td>"
        f"<td>{escape(str(r.get('state', '')))}</td>"
        f"<td class='num'>{escape(iters_s)}</td>"
        f"<td class='num'>{avg}</td>"
        f"<td class='num'>{p99}</td></tr>"
    )


def _render_bw_summary(s: Dict[str, Any]) -> str:
    avg = _fmt(s.get("bw_avg_gbps"), 2)
    mn = _fmt(s.get("bw_min_gbps"), 2)
    mx = _fmt(s.get("bw_max_gbps"), 2)
    mr_avg = _fmt(s.get("msgrate_avg_mpps"), 4)
    n = s.get("samples") or s.get("n") or len(s.get("rows") or []) or "?"
    return (
        f"<tr class='summary'><td>Σ</td>"
        f"<td>{escape(str(n))} samples</td>"
        f"<td class='num'>avg {avg} (min {mn}, max {mx})</td>"
        f"<td class='num'>{mr_avg}</td>"
        f"<td class='num'>—</td></tr>"
    )


def _render_lat_summary(s: Dict[str, Any]) -> str:
    avg = _fmt(s.get("lat_avg_us"), 2)
    n = s.get("samples") or s.get("n") or "?"
    return (
        f"<tr class='summary'><td>Σ</td>"
        f"<td>{escape(str(n))} samples</td>"
        f"<td class='num'>—</td>"
        f"<td class='num'>avg {avg}</td>"
        f"<td class='num'>—</td></tr>"
    )


def _fmt(v: Any, places: int) -> str:
    if isinstance(v, (int, float)):
        return f"{float(v):.{places}f}"
    return "—"
